server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      platform: 'postgres'
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
          starttls:
            enable: true
  datasource:
    username: ${POSTGRESQL_USERNAME_MACHINE}
#    ${POSTGRESQL_USERNAME}

    password: ${POSTGRESQL_PASSWORD_MACHINE}
#    ${POSTGRESQL_PASSWORD}
    url: ${POSTGRESQL_URL_MACHINE}
#      ${POSTGRESQL_URL}
    driver-class-name: org.postgresql.Driver
  redis:
    host: "localhost"
    port: 6379
  cache:
    redis:
      time-to-live: 60000

security:
  jwtSecret: ${JWT_SECRET}
