version: '3'
services:
  server:
    image: ${CI_REGISTRY_IMAGE}:${CI_IMAGE_TAG}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /home/spotify/cdn/:/data/
    environment:
      - POSTGRESQL_URL=${POSTGRESQL_URL_MACHINE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME_MACHINE}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD_MACHINE}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"